apiVersion: apps/v1
kind: Deployment
metadata:
  name: oukou
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oukou
  template:
    metadata:
      labels:
        app: oukou
    spec:
      containers:
      - image: okteto.dev/oukou:latest
        name: oukou
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "770fc9a7-3639-46fb-a685-56cba929b3f7"
        - name: Vless_Path
          value: "/vlesss233"
        - name: Vmess_UUID
          value: "770fc9a7-3639-46fb-a685-56cba929b3f7"
        - name: Vmess_Path
          value: "/vmesss244"
        - name: Share_Path
          value: "/share233"
